const inv_index = {
    "206":[
       "index.html"
    ],
    "crawler":[
       "index.html"
    ],
    "home":[
       "UCBerkeley.html",
       "Campanile.html",
       "MIMS.html",
       "SouthHall.html",
       "ISchool.html",
       "Berkeley.html",
       "CityOfBerkeley.html",
       "index.html",
       "information.html",
       "BerkeleyCollege.html"
    ],
    "page":[
       "information.html",
       "index.html"
    ],
    "the":[
       "UCBerkeley.html",
       "Campanile.html",
       "MIMS.html",
       "SouthHall.html",
       "ISchool.html",
       "CityOfBerkeley.html",
       "index.html",
       "information.html",
       "BerkeleyCollege.html"
    ],
    "where":[
       "index.html"
    ],
    "any":[
       "UCBerkeley.html",
       "index.html"
    ],
    "information":[
       "information.html",
       "MIMS.html",
       "ISchool.html",
       "index.html"
    ],
    "can":[
       "Berkeley.html",
       "index.html"
    ],
    "be":[
       "Berkeley.html",
       "index.html"
    ],
    "found":[
       "index.html"
    ],
    "is":[
       "UCBerkeley.html",
       "Campanile.html",
       "MIMS.html",
       "SouthHall.html",
       "ISchool.html",
       "index.html",
       "CityOfBerkeley.html",
       "BerkeleyCollege.html"
    ],
    "homepage":[
       "index.html"
    ],
    "your":[
       "index.html"
    ],
    "will":[
       "index.html"
    ],
    "start":[
       "index.html"
    ],
    "follow":[
       "index.html"
    ],
    "links":[
       "index.html"
    ],
    "to":[
       "UCBerkeley.html",
       "Campanile.html",
       "MIMS.html",
       "SouthHall.html",
       "ISchool.html",
       "Berkeley.html",
       "CityOfBerkeley.html",
       "index.html",
       "information.html"
    ],
    "discover":[
       "index.html"
    ],
    "whats":[
       "index.html"
    ],
    "on":[
       "UCBerkeley.html",
       "Campanile.html",
       "SouthHall.html",
       "index.html",
       "CityOfBerkeley.html"
    ],
    "site":[
       "CityOfBerkeley.html",
       "index.html"
    ],
    "there":[
       "information.html"
    ],
    "are":[
       "MIMS.html",
       "UCBerkeley.html",
       "Campanile.html",
       "information.html"
    ],
    "many":[
       "information.html"
    ],
    "great":[
       "information.html"
    ],
    "things":[
       "Berkeley.html",
       "information.html"
    ],
    "learn":[
       "information.html"
    ],
    "about":[
       "SouthHall.html",
       "ISchool.html",
       "Campanile.html",
       "information.html"
    ],
    "here":[
       "information.html"
    ],
    "berkeley":[
       "UCBerkeley.html",
       "information.html",
       "ISchool.html",
       "Berkeley.html",
       "CityOfBerkeley.html",
       "BerkeleyCollege.html"
    ],
    "uc":[
       "ISchool.html",
       "Berkeley.html",
       "UCBerkeley.html",
       "information.html"
    ],
    "school":[
       "MIMS.html",
       "ISchool.html",
       "BerkeleyCollege.html",
       "information.html"
    ],
    "of":[
       "UCBerkeley.html",
       "Campanile.html",
       "MIMS.html",
       "information.html",
       "ISchool.html",
       "SouthHall.html",
       "CityOfBerkeley.html",
       "BerkeleyCollege.html"
    ],
    "masters":[
       "MIMS.html",
       "information.html"
    ],
    "management":[
       "MIMS.html",
       "ISchool.html",
       "BerkeleyCollege.html",
       "information.html"
    ],
    "and":[
       "UCBerkeley.html",
       "Campanile.html",
       "MIMS.html",
       "information.html",
       "ISchool.html",
       "SouthHall.html",
       "CityOfBerkeley.html",
       "BerkeleyCollege.html"
    ],
    "systems":[
       "MIMS.html",
       "ISchool.html",
       "information.html"
    ],
    "degree":[
       "UCBerkeley.html",
       "MIMS.html",
       "ISchool.html",
       "information.html",
       "BerkeleyCollege.html"
    ],
    "which":[
       "Berkeley.html",
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "refers":[
       "Berkeley.html"
    ],
    "a":[
       "UCBerkeley.html",
       "Campanile.html",
       "MIMS.html",
       "ISchool.html",
       "Berkeley.html",
       "CityOfBerkeley.html",
       "BerkeleyCollege.html"
    ],
    "few":[
       "Berkeley.html"
    ],
    "different":[
       "Berkeley.html"
    ],
    "you":[
       "Berkeley.html"
    ],
    "more":[
       "Berkeley.html",
       "UCBerkeley.html",
       "Campanile.html"
    ],
    "specific":[
       "Berkeley.html"
    ],
    "california":[
       "UCBerkeley.html",
       "SouthHall.html",
       "ISchool.html",
       "Berkeley.html",
       "CityOfBerkeley.html"
    ],
    "college":[
       "BerkeleyCollege.html",
       "Berkeley.html",
       "UCBerkeley.html",
       "Campanile.html"
    ],
    "or":[
       "ISchool.html",
       "UCBerkeley.html"
    ],
    "i":[
       "MIMS.html",
       "ISchool.html"
    ],
    "graduate":[
       "ISchool.html",
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "offering":[
       "ISchool.html"
    ],
    "mims":[
       "MIMS.html",
       "ISchool.html"
    ],
    "in":[
       "UCBerkeley.html",
       "Campanile.html",
       "MIMS.html",
       "SouthHall.html",
       "ISchool.html",
       "CityOfBerkeley.html",
       "BerkeleyCollege.html"
    ],
    "addition":[
       "ISchool.html"
    ],
    "mids":[
       "ISchool.html"
    ],
    "mics":[
       "ISchool.html"
    ],
    "degrees":[
       "ISchool.html",
       "BerkeleyCollege.html"
    ],
    "researchoriented":[
       "ISchool.html"
    ],
    "phd":[
       "ISchool.html"
    ],
    "at":[
       "MIMS.html",
       "ISchool.html",
       "CityOfBerkeley.html"
    ],
    "university":[
       "SouthHall.html",
       "ISchool.html",
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "created":[
       "ISchool.html"
    ],
    "1994":[
       "ISchool.html"
    ],
    "berkeleys":[
       "ISchool.html",
       "UCBerkeley.html"
    ],
    "newest":[
       "ISchool.html"
    ],
    "it":[
       "UCBerkeley.html",
       "Campanile.html",
       "SouthHall.html",
       "ISchool.html",
       "CityOfBerkeley.html"
    ],
    "was":[
       "SouthHall.html",
       "ISchool.html",
       "Campanile.html",
       "CityOfBerkeley.html"
    ],
    "previously":[
       "ISchool.html"
    ],
    "known":[
       "SouthHall.html",
       "ISchool.html",
       "Campanile.html"
    ],
    "as":[
       "UCBerkeley.html",
       "Campanile.html",
       "MIMS.html",
       "SouthHall.html",
       "ISchool.html",
       "CityOfBerkeley.html"
    ],
    "sims":[
       "ISchool.html"
    ],
    "until":[
       "ISchool.html"
    ],
    "2006":[
       "ISchool.html"
    ],
    "its":[
       "ISchool.html",
       "UCBerkeley.html",
       "Campanile.html"
    ],
    "roots":[
       "ISchool.html"
    ],
    "trace":[
       "ISchool.html"
    ],
    "back":[
       "ISchool.html"
    ],
    "librarianship":[
       "ISchool.html"
    ],
    "founded":[
       "ISchool.html",
       "BerkeleyCollege.html",
       "UCBerkeley.html"
    ],
    "1920s":[
       "ISchool.html"
    ],
    "program":[
       "MIMS.html",
       "ISchool.html"
    ],
    "located":[
       "SouthHall.html",
       "ISchool.html",
       "UCBerkeley.html"
    ],
    "south":[
       "SouthHall.html",
       "ISchool.html",
       "CityOfBerkeley.html"
    ],
    "hall":[
       "SouthHall.html",
       "ISchool.html"
    ],
    "near":[
       "SouthHall.html",
       "ISchool.html"
    ],
    "sather":[
       "SouthHall.html",
       "ISchool.html",
       "Campanile.html"
    ],
    "tower":[
       "SouthHall.html",
       "ISchool.html",
       "Campanile.html"
    ],
    "center":[
       "ISchool.html"
    ],
    "campus":[
       "SouthHall.html",
       "ISchool.html",
       "UCBerkeley.html",
       "Campanile.html"
    ],
    "master":[
       "MIMS.html",
       "Campanile.html"
    ],
    "48":[
       "MIMS.html"
    ],
    "unit":[
       "MIMS.html"
    ],
    "twoyear":[
       "MIMS.html"
    ],
    "designed":[
       "MIMS.html",
       "Campanile.html"
    ],
    "train":[
       "MIMS.html"
    ],
    "students":[
       "MIMS.html",
       "UCBerkeley.html"
    ],
    "for":[
       "MIMS.html",
       "SouthHall.html",
       "UCBerkeley.html"
    ],
    "careers":[
       "MIMS.html"
    ],
    "professionals":[
       "MIMS.html"
    ],
    "who":[
       "MIMS.html",
       "SouthHall.html"
    ],
    "complete":[
       "MIMS.html"
    ],
    "awarded":[
       "MIMS.html"
    ],
    "during":[
       "MIMS.html"
    ],
    "first":[
       "MIMS.html",
       "Campanile.html"
    ],
    "year":[
       "MIMS.html"
    ],
    "take":[
       "MIMS.html"
    ],
    "range":[
       "MIMS.html",
       "UCBerkeley.html"
    ],
    "required":[
       "MIMS.html"
    ],
    "elective":[
       "MIMS.html"
    ],
    "courses":[
       "MIMS.html",
       "BerkeleyCollege.html"
    ],
    "second":[
       "MIMS.html"
    ],
    "may":[
       "MIMS.html"
    ],
    "choose":[
       "MIMS.html"
    ],
    "from":[
       "MIMS.html"
    ],
    "both":[
       "MIMS.html",
       "UCBerkeley.html"
    ],
    "other":[
       "MIMS.html",
       "UCBerkeley.html"
    ],
    "departments":[
       "MIMS.html"
    ],
    "final":[
       "MIMS.html"
    ],
    "requirement":[
       "MIMS.html"
    ],
    "completion":[
       "MIMS.html"
    ],
    "capstone":[
       "MIMS.html"
    ],
    "project":[
       "MIMS.html"
    ],
    "city":[
       "CityOfBerkeley.html"
    ],
    "east":[
       "CityOfBerkeley.html"
    ],
    "shore":[
       "CityOfBerkeley.html"
    ],
    "san":[
       "UCBerkeley.html",
       "Campanile.html",
       "CityOfBerkeley.html"
    ],
    "francisco":[
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "bay":[
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "northern":[
       "CityOfBerkeley.html"
    ],
    "california—in":[
       "CityOfBerkeley.html"
    ],
    "alameda":[
       "CityOfBerkeley.html"
    ],
    "county":[
       "CityOfBerkeley.html"
    ],
    "bordered":[
       "CityOfBerkeley.html"
    ],
    "by":[
       "SouthHall.html",
       "Campanile.html",
       "CityOfBerkeley.html"
    ],
    "cities":[
       "CityOfBerkeley.html"
    ],
    "oakland":[
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "emeryville":[
       "CityOfBerkeley.html"
    ],
    "north":[
       "CityOfBerkeley.html"
    ],
    "albany":[
       "CityOfBerkeley.html"
    ],
    "unincorporated":[
       "CityOfBerkeley.html"
    ],
    "community":[
       "CityOfBerkeley.html"
    ],
    "kensington":[
       "CityOfBerkeley.html"
    ],
    "eastern":[
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "limit":[
       "CityOfBerkeley.html"
    ],
    "coincides":[
       "CityOfBerkeley.html"
    ],
    "with":[
       "UCBerkeley.html",
       "Campanile.html",
       "CityOfBerkeley.html"
    ],
    "contra":[
       "CityOfBerkeley.html"
    ],
    "costa":[
       "CityOfBerkeley.html"
    ],
    "border":[
       "CityOfBerkeley.html"
    ],
    "generally":[
       "CityOfBerkeley.html"
    ],
    "follows":[
       "CityOfBerkeley.html"
    ],
    "ridge":[
       "CityOfBerkeley.html"
    ],
    "line":[
       "CityOfBerkeley.html"
    ],
    "hills":[
       "CityOfBerkeley.html"
    ],
    "population":[
       "CityOfBerkeley.html"
    ],
    "112580":[
       "CityOfBerkeley.html"
    ],
    "2010":[
       "CityOfBerkeley.html"
    ],
    "census":[
       "CityOfBerkeley.html"
    ],
    "named":[
       "CityOfBerkeley.html"
    ],
    "after":[
       "CityOfBerkeley.html"
    ],
    "bishop":[
       "CityOfBerkeley.html"
    ],
    "george":[
       "CityOfBerkeley.html"
    ],
    "oldest":[
       "SouthHall.html",
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "system":[
       "SouthHall.html",
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "lawrence":[
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "national":[
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "laboratory":[
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "also":[
       "SouthHall.html",
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "theological":[
       "CityOfBerkeley.html"
    ],
    "union":[
       "CityOfBerkeley.html"
    ],
    "noted":[
       "CityOfBerkeley.html"
    ],
    "one":[
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "most":[
       "CityOfBerkeley.html"
    ],
    "politically":[
       "CityOfBerkeley.html"
    ],
    "liberal":[
       "BerkeleyCollege.html",
       "CityOfBerkeley.html"
    ],
    "nation":[
       "UCBerkeley.html",
       "CityOfBerkeley.html"
    ],
    "referred":[
       "UCBerkeley.html"
    ],
    "simply":[
       "UCBerkeley.html"
    ],
    "cal":[
       "UCBerkeley.html"
    ],
    "public":[
       "UCBerkeley.html",
       "Campanile.html"
    ],
    "research":[
       "UCBerkeley.html"
    ],
    "united":[
       "UCBerkeley.html"
    ],
    "states":[
       "UCBerkeley.html"
    ],
    "occupies":[
       "UCBerkeley.html"
    ],
    "1232":[
       "UCBerkeley.html"
    ],
    "acres":[
       "UCBerkeley.html"
    ],
    "499":[
       "UCBerkeley.html"
    ],
    "ha":[
       "UCBerkeley.html"
    ],
    "side":[
       "UCBerkeley.html"
    ],
    "central":[
       "UCBerkeley.html"
    ],
    "resting":[
       "UCBerkeley.html"
    ],
    "178":[
       "UCBerkeley.html"
    ],
    "72":[
       "UCBerkeley.html"
    ],
    "flagship":[
       "UCBerkeley.html"
    ],
    "institution":[
       "BerkeleyCollege.html",
       "UCBerkeley.html"
    ],
    "10":[
       "UCBerkeley.html"
    ],
    "only":[
       "UCBerkeley.html"
    ],
    "two":[
       "UCBerkeley.html"
    ],
    "campuses":[
       "UCBerkeley.html"
    ],
    "operating":[
       "UCBerkeley.html"
    ],
    "semester":[
       "UCBerkeley.html"
    ],
    "calendar":[
       "UCBerkeley.html"
    ],
    "being":[
       "UCBerkeley.html"
    ],
    "merced":[
       "UCBerkeley.html"
    ],
    "established":[
       "UCBerkeley.html"
    ],
    "1868":[
       "UCBerkeley.html"
    ],
    "result":[
       "UCBerkeley.html"
    ],
    "merger":[
       "UCBerkeley.html"
    ],
    "private":[
       "UCBerkeley.html"
    ],
    "agricultural":[
       "UCBerkeley.html"
    ],
    "mining":[
       "UCBerkeley.html"
    ],
    "mechanical":[
       "UCBerkeley.html"
    ],
    "arts":[
       "BerkeleyCollege.html",
       "UCBerkeley.html"
    ],
    "offers":[
       "BerkeleyCollege.html",
       "UCBerkeley.html"
    ],
    "approximately":[
       "UCBerkeley.html"
    ],
    "350":[
       "UCBerkeley.html"
    ],
    "undergraduate":[
       "UCBerkeley.html"
    ],
    "programs":[
       "BerkeleyCollege.html",
       "UCBerkeley.html"
    ],
    "wide":[
       "UCBerkeley.html"
    ],
    "disciplines":[
       "UCBerkeley.html"
    ],
    "has":[
       "UCBerkeley.html",
       "Campanile.html"
    ],
    "been":[
       "UCBerkeley.html",
       "Campanile.html"
    ],
    "charged":[
       "UCBerkeley.html"
    ],
    "providing":[
       "UCBerkeley.html"
    ],
    "classical":[
       "UCBerkeley.html"
    ],
    "practical":[
       "UCBerkeley.html"
    ],
    "education":[
       "BerkeleyCollege.html",
       "UCBerkeley.html"
    ],
    "people":[
       "UCBerkeley.html"
    ],
    "comanages":[
       "UCBerkeley.html"
    ],
    "three":[
       "UCBerkeley.html"
    ],
    "department":[
       "UCBerkeley.html"
    ],
    "energy":[
       "UCBerkeley.html"
    ],
    "laboratories":[
       "UCBerkeley.html"
    ],
    "including":[
       "BerkeleyCollege.html",
       "UCBerkeley.html"
    ],
    "los":[
       "UCBerkeley.html"
    ],
    "alamos":[
       "UCBerkeley.html"
    ],
    "livermore":[
       "UCBerkeley.html"
    ],
    "us":[
       "UCBerkeley.html"
    ],
    "among":[
       "UCBerkeley.html"
    ],
    "alumni":[
       "UCBerkeley.html"
    ],
    "faculty":[
       "UCBerkeley.html"
    ],
    "researchers":[
       "UCBerkeley.html"
    ],
    "nobel":[
       "UCBerkeley.html"
    ],
    "laureates":[
       "UCBerkeley.html"
    ],
    "110":[
       "UCBerkeley.html"
    ],
    "turing":[
       "UCBerkeley.html"
    ],
    "award":[
       "UCBerkeley.html"
    ],
    "winners":[
       "UCBerkeley.html"
    ],
    "25":[
       "UCBerkeley.html"
    ],
    "fields":[
       "UCBerkeley.html"
    ],
    "medalists":[
       "UCBerkeley.html"
    ],
    "14":[
       "UCBerkeley.html"
    ],
    "wolf":[
       "UCBerkeley.html"
    ],
    "prize":[
       "UCBerkeley.html"
    ],
    "30":[
       "UCBerkeley.html"
    ],
    "than":[
       "UCBerkeley.html"
    ],
    "affiliated":[
       "UCBerkeley.html"
    ],
    "34":[
       "UCBerkeley.html"
    ],
    "pulitzer":[
       "UCBerkeley.html"
    ],
    "prizes":[
       "UCBerkeley.html"
    ],
    "19":[
       "UCBerkeley.html"
    ],
    "academy":[
       "UCBerkeley.html"
    ],
    "awards":[
       "UCBerkeley.html"
    ],
    "macarthur":[
       "UCBerkeley.html"
    ],
    "genius":[
       "UCBerkeley.html"
    ],
    "grants":[
       "UCBerkeley.html"
    ],
    "108":[
       "UCBerkeley.html"
    ],
    "medals":[
       "UCBerkeley.html"
    ],
    "science":[
       "UCBerkeley.html"
    ],
    "68":[
       "UCBerkeley.html"
    ],
    "date":[
       "UCBerkeley.html"
    ],
    "associated":[
       "UCBerkeley.html"
    ],
    "6":[
       "UCBerkeley.html"
    ],
    "chemical":[
       "UCBerkeley.html"
    ],
    "elements":[
       "UCBerkeley.html"
    ],
    "periodic":[
       "UCBerkeley.html"
    ],
    "table":[
       "UCBerkeley.html"
    ],
    "californium":[
       "UCBerkeley.html"
    ],
    "seaborgium":[
       "UCBerkeley.html"
    ],
    "berkelium":[
       "UCBerkeley.html"
    ],
    "einsteinium":[
       "UCBerkeley.html"
    ],
    "fermium":[
       "UCBerkeley.html"
    ],
    "lawrencium":[
       "UCBerkeley.html"
    ],
    "lab":[
       "UCBerkeley.html"
    ],
    "discovered":[
       "UCBerkeley.html"
    ],
    "16":[
       "UCBerkeley.html"
    ],
    "total":[
       "UCBerkeley.html"
    ],
    "–":[
       "UCBerkeley.html"
    ],
    "world":[
       "UCBerkeley.html",
       "Campanile.html"
    ],
    "produced":[
       "UCBerkeley.html"
    ],
    "seven":[
       "UCBerkeley.html",
       "Campanile.html"
    ],
    "heads":[
       "UCBerkeley.html"
    ],
    "state":[
       "UCBerkeley.html"
    ],
    "government":[
       "UCBerkeley.html"
    ],
    "six":[
       "UCBerkeley.html"
    ],
    "chief":[
       "UCBerkeley.html"
    ],
    "justices":[
       "UCBerkeley.html"
    ],
    "justice":[
       "BerkeleyCollege.html",
       "UCBerkeley.html"
    ],
    "earl":[
       "UCBerkeley.html"
    ],
    "warren":[
       "UCBerkeley.html"
    ],
    "22":[
       "UCBerkeley.html"
    ],
    "cabinetlevel":[
       "UCBerkeley.html"
    ],
    "officials":[
       "UCBerkeley.html"
    ],
    "11":[
       "UCBerkeley.html"
    ],
    "governors":[
       "UCBerkeley.html"
    ],
    "living":[
       "UCBerkeley.html"
    ],
    "billionaires":[
       "UCBerkeley.html"
    ],
    "leading":[
       "UCBerkeley.html"
    ],
    "producer":[
       "UCBerkeley.html"
    ],
    "fulbright":[
       "UCBerkeley.html"
    ],
    "scholars":[
       "UCBerkeley.html"
    ],
    "fellows":[
       "UCBerkeley.html"
    ],
    "marshall":[
       "UCBerkeley.html"
    ],
    "widely":[
       "UCBerkeley.html"
    ],
    "recognized":[
       "UCBerkeley.html"
    ],
    "their":[
       "UCBerkeley.html"
    ],
    "entrepreneurship":[
       "BerkeleyCollege.html",
       "UCBerkeley.html"
    ],
    "have":[
       "SouthHall.html",
       "UCBerkeley.html"
    ],
    "numerous":[
       "UCBerkeley.html"
    ],
    "notable":[
       "UCBerkeley.html"
    ],
    "companies":[
       "UCBerkeley.html"
    ],
    "apple":[
       "UCBerkeley.html"
    ],
    "tesla":[
       "UCBerkeley.html"
    ],
    "intel":[
       "UCBerkeley.html"
    ],
    "ebay":[
       "UCBerkeley.html"
    ],
    "softbank":[
       "UCBerkeley.html"
    ],
    "aig":[
       "UCBerkeley.html"
    ],
    "morgan":[
       "UCBerkeley.html"
    ],
    "stanley":[
       "UCBerkeley.html"
    ],
    "athletic":[
       "UCBerkeley.html"
    ],
    "teams":[
       "UCBerkeley.html"
    ],
    "compete":[
       "UCBerkeley.html"
    ],
    "golden":[
       "UCBerkeley.html"
    ],
    "bears":[
       "UCBerkeley.html"
    ],
    "primarily":[
       "UCBerkeley.html"
    ],
    "pac12":[
       "UCBerkeley.html"
    ],
    "conference":[
       "UCBerkeley.html"
    ],
    "won":[
       "UCBerkeley.html"
    ],
    "107":[
       "UCBerkeley.html"
    ],
    "championships":[
       "UCBerkeley.html"
    ],
    "223":[
       "UCBerkeley.html"
    ],
    "olympic":[
       "UCBerkeley.html"
    ],
    "121":[
       "UCBerkeley.html"
    ],
    "gold":[
       "UCBerkeley.html"
    ],
    "higher":[
       "BerkeleyCollege.html"
    ],
    "1931":[
       "BerkeleyCollege.html"
    ],
    "specializing":[
       "BerkeleyCollege.html"
    ],
    "business":[
       "BerkeleyCollege.html"
    ],
    "professional":[
       "BerkeleyCollege.html"
    ],
    "studies":[
       "BerkeleyCollege.html"
    ],
    "associates":[
       "BerkeleyCollege.html"
    ],
    "bachelors":[
       "BerkeleyCollege.html"
    ],
    "provides":[
       "BerkeleyCollege.html"
    ],
    "academic":[
       "BerkeleyCollege.html"
    ],
    "administration":[
       "BerkeleyCollege.html"
    ],
    "general":[
       "BerkeleyCollege.html"
    ],
    "accounting":[
       "BerkeleyCollege.html"
    ],
    "financial":[
       "BerkeleyCollege.html"
    ],
    "services":[
       "BerkeleyCollege.html"
    ],
    "marketing":[
       "BerkeleyCollege.html"
    ],
    "communications":[
       "BerkeleyCollege.html"
    ],
    "concentrations":[
       "BerkeleyCollege.html"
    ],
    "environmental":[
       "BerkeleyCollege.html",
       "Campanile.html"
    ],
    "nonprofit":[
       "BerkeleyCollege.html"
    ],
    "human":[
       "BerkeleyCollege.html"
    ],
    "resources":[
       "BerkeleyCollege.html"
    ],
    "international":[
       "BerkeleyCollege.html"
    ],
    "fashion":[
       "BerkeleyCollege.html"
    ],
    "through":[
       "BerkeleyCollege.html"
    ],
    "larry":[
       "BerkeleyCollege.html"
    ],
    "l":[
       "BerkeleyCollege.html"
    ],
    "luing":[
       "BerkeleyCollege.html"
    ],
    "health":[
       "BerkeleyCollege.html"
    ],
    "criminal":[
       "BerkeleyCollege.html"
    ],
    "legal":[
       "BerkeleyCollege.html"
    ],
    "graphic":[
       "BerkeleyCollege.html"
    ],
    "design":[
       "BerkeleyCollege.html",
       "Campanile.html"
    ],
    "interior":[
       "BerkeleyCollege.html"
    ],
    "humanities":[
       "BerkeleyCollege.html"
    ],
    "mathematicsscience":[
       "BerkeleyCollege.html"
    ],
    "social":[
       "BerkeleyCollege.html"
    ],
    "sciences":[
       "BerkeleyCollege.html"
    ],
    "english":[
       "BerkeleyCollege.html"
    ],
    "foreign":[
       "BerkeleyCollege.html"
    ],
    "languages":[
       "BerkeleyCollege.html"
    ],
    "built":[
       "SouthHall.html"
    ],
    "1873":[
       "SouthHall.html"
    ],
    "building":[
       "SouthHall.html"
    ],
    "heart":[
       "SouthHall.html"
    ],
    "doe":[
       "SouthHall.html"
    ],
    "library":[
       "SouthHall.html"
    ],
    "campanile":[
       "SouthHall.html",
       "Campanile.html"
    ],
    "smallest":[
       "SouthHall.html"
    ],
    "bear":[
       "SouthHall.html"
    ],
    "statue":[
       "SouthHall.html"
    ],
    "small":[
       "SouthHall.html"
    ],
    "added":[
       "SouthHall.html"
    ],
    "michael":[
       "SouthHall.html"
    ],
    "h":[
       "SouthHall.html"
    ],
    "casey":[
       "SouthHall.html"
    ],
    "did":[
       "SouthHall.html"
    ],
    "ornamental":[
       "SouthHall.html"
    ],
    "castings":[
       "SouthHall.html"
    ],
    "restored":[
       "SouthHall.html"
    ],
    "facade":[
       "SouthHall.html"
    ],
    "1997":[
       "SouthHall.html"
    ],
    "aka":[
       "Campanile.html"
    ],
    "bell":[
       "Campanile.html"
    ],
    "clock":[
       "Campanile.html"
    ],
    "commonly":[
       "Campanile.html"
    ],
    "due":[
       "Campanile.html"
    ],
    "resemblance":[
       "Campanile.html"
    ],
    "di":[
       "Campanile.html"
    ],
    "marco":[
       "Campanile.html"
    ],
    "venice":[
       "Campanile.html"
    ],
    "completed":[
       "Campanile.html"
    ],
    "1914":[
       "Campanile.html"
    ],
    "opened":[
       "Campanile.html"
    ],
    "1917":[
       "Campanile.html"
    ],
    "stands":[
       "Campanile.html"
    ],
    "307":[
       "Campanile.html"
    ],
    "feet":[
       "Campanile.html"
    ],
    "936":[
       "Campanile.html"
    ],
    "m":[
       "Campanile.html"
    ],
    "tall":[
       "Campanile.html"
    ],
    "making":[
       "Campanile.html"
    ],
    "third":[
       "Campanile.html"
    ],
    "tallest":[
       "Campanile.html"
    ],
    "clocktower":[
       "Campanile.html"
    ],
    "john":[
       "Campanile.html"
    ],
    "galen":[
       "Campanile.html"
    ],
    "howard":[
       "Campanile.html"
    ],
    "founder":[
       "Campanile.html"
    ],
    "marks":[
       "Campanile.html"
    ],
    "secondary":[
       "Campanile.html"
    ],
    "axis":[
       "Campanile.html"
    ],
    "his":[
       "Campanile.html"
    ],
    "original":[
       "Campanile.html"
    ],
    "beauxarts":[
       "Campanile.html"
    ],
    "plan":[
       "Campanile.html"
    ],
    "since":[
       "Campanile.html"
    ],
    "then":[
       "Campanile.html"
    ],
    "major":[
       "Campanile.html"
    ],
    "point":[
       "Campanile.html"
    ],
    "orientation":[
       "Campanile.html"
    ],
    "almost":[
       "Campanile.html"
    ],
    "every":[
       "Campanile.html"
    ],
    "floors":[
       "Campanile.html"
    ],
    "an":[
       "Campanile.html"
    ],
    "observation":[
       "Campanile.html"
    ],
    "deck":[
       "Campanile.html"
    ],
    "eighth":[
       "Campanile.html"
    ],
    "floor":[
       "Campanile.html"
    ],
    "some":[
       "Campanile.html"
    ],
    "used":[
       "Campanile.html"
    ],
    "store":[
       "Campanile.html"
    ],
    "fossils":[
       "Campanile.html"
    ]
}

document.getElementById("searchForm").addEventListener("submit", (event) => {
    event.preventDefault();

    let query = document.getElementById("searchBar").value.toString().toLowerCase();

    if (query in inv_index) {
        const results = inv_index[query];

        document.getElementById("searchResult").innerHTML = results.map((result) => 
            `<div><a href="https://people.ischool.berkeley.edu/~chuang/i206/b5/${result}">${result}</a></div>`
        ).join('')
    } else {
        document.getElementById("searchResult").innerHTML = "No results found"
    }

    document.getElementById("searchBar").value = '';
    
})